name: Changesets

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Install only changesets
        run: npm install --no-save @changesets/cli

      - name: Check changesets
        run: |
          if [ ! -e .changeset/*.md ]; then
            echo "Нет changeset-файла! Добавьте его."
            exit 1
          fi

      - name: Bump changes version
        run: |
          npx changeset version
          echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update image tag to ${{ env.TAG }} [skip ci]'

      - name: Create github release
        uses: ncipollo/release-action@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "${{ env.TAG }}"
          tag: "${{ env.TAG }}"

  deploy:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - run: echo released!
