name: Changesets

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install only changesets
        run: npm install --no-save @changesets/cli

      - name: Check changesets
        run: npx changeset status

      - name: Bump changes version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          prev_version=$(jq -r '.version' package.json)
          npx changeset version
          next_version=$(jq -r '.version' package.json)
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(deps): bump kaiten $prev_version -> $next_version" -m "[skip ci]"
            git push
          fi
