name: Changesets

on:
  workflow_call:
    outputs:
      commit_sha:
        value: ${{ jobs.version-bump.outputs.commit_sha }}

jobs:
  version-bump:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_sha.outputs.commit_sha }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Install only changesets
        run: |
          npm install --global @changesets/cli
          npx @changesets/cli --version

      - name: Bump changes version
        run: |
          npx @changesets/cli version
          echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update image tag to ${{ env.TAG }} [skip ci]'

      - name: Get new commit SHA
        id: get_sha
        run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create github release
        uses: ncipollo/release-action@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "${{ env.TAG }}"
          tag: "${{ env.TAG }}"
