name: Changesets

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  version-bump:
    uses: ./.github/workflows/changesets.yml
    secrets: inherit


  deploy:
    needs: version-bump
    uses: ./.github/workflows/deploy.yml
