name: Changesets

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: git fetch origin master

      - name: Compare package.json version with master
        run: |
          current_version=$(jq -r .version package.json)
          master_version=$(git show origin/master:package.json | jq -r .version)
          echo "Current version: $current_version"
          echo "Master version: $master_version"
          if [ "$current_version" != "$master_version" ]; then
            echo "The version in package.json has changed compared to master. Please use 'yarn changeset'."
            exit 1
          fi

      - name: Check changesets
        run: |
          if ! find .changeset -maxdepth 1 -type f -name '*.md' ! -name 'README.md' | grep -q .; then
            echo "No changeset file found. Please use 'yarn changeset'."
            exit 1
          fi

