name: Changesets

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  version-bump:
    uses: .github/workflows/changesets.yml
    secrets: inherit
    outputs:
      commit_sha: ${{ jobs.version-bump.outputs.commit_sha }}

  deploy:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          ref: ${{ needs.version-bump.outputs.commit_sha }}

      - name: Compare package.json version with master
        run: |
          current_version=$(jq -r .version package.json)
          echo "Current version: $current_version"
